ALTER TABLE jobs ADD COLUMN IF NOT EXISTS worker_token VARCHAR;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS attempts INTEGER DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS max_attempts INTEGER DEFAULT 3;
CREATE INDEX IF NOT EXISTS idx_jobs_worker_token ON jobs(worker_token);
